### ISSUE TITLE
Inline cloud-config into template definition

### ISSUE THREAD

**Issue by degremont** [cea-hpc/pcocc#4]
It could make template management easier if cloud init configuration could be declared directly into template definition, avoiding to manage several file for only one template. As both are using yaml syntax, this should not be very difficult.

Either you pick a new keyword for that (`cloud-config`? `cloud-init`?) or you keep the same one and detect if its value its a string or a dict.

```yaml
centos:
  image: /my/image
  user-data:

    bootcmd:
      - cloud-init-per instance yumclean rm -f /etc/yum.repos.d/*
    packages:
     - vim
     - pigz
    ...
```
